import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className=" bg-amber-300  pt-7 pb-7">
          <Link href={"/"} className=" flex flex-row text-5xl">
            Web Developer
          </Link>

          <div className=" flex justify-end">
            {" "}
            <button className=" pl-2.5 pr-2.5 text-2xl hover:text-red-700">
              <Link href={"/"}>Home</Link>
            </button>
            <button className=" pl-2.5 pr-2.5 text-2xl hover:text-red-700">
              <Link href={"/About"}>About</Link>
            </button>
            <button className=" pr-2.5 pl-2.5 text-2xl hover:text-red-700">
              <Link href={"/Contact"}>Contact</Link>
            </button>
            <button className=" pr-2.5 pl-2.5 text-2xl hover:text-red-700">
              <Link href={"/Skills"}>Skills</Link>
            </button>
            <button className=" pr-2.5 pl-2.5 text-2xl hover:text-red-700">
              <Link href={"/Why"}>Why me</Link>
            </button>
          </div>
        </header>
        {children}
        <footer className=" flex justify-center pt-7 pb-7 bg-black text-white hover:*:text-red-600">
          &copy; 2025 Ssebayigga Sharif. All rights reserved.
          <p className=" pl-3.5 pr-3.5">
            <Link href={"https://github.com/ssebayigga-sharif"}>Github</Link>
          </p>
          <p className=" pr-3.5 pl-3.5">
            <Link
              href={"https://www.linkedin.com/in/sharif-ssebayigga-7025a6375/"}
            >
              LinkedIn
            </Link>
          </p>
          <p className=" pl-3.5 pr-3.5"> sharifsseba@gmail.com.</p>
        </footer>
      </body>
    </html>
  );
}
