import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: {
    icon: "/saaarif.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="pt-7 pb-7 bg-black text-white">
          <button className=" flex flex-row text-5xl hover:text-shadow-cyan-600">
            <div className="flex items-center space-x-2">
              <Image
                src="/saaarif.png"
                alt="Sharif Logo"
                width={40}
                height={40}
                className="rounded-full"
              />
            </div>
            <Link href={"/"}>Web Developer</Link>
          </button>

          <div className=" flex justify-end">
            {" "}
            <button className=" pl-2.5 pr-2.5 text-2xl hover:text-red-700">
              <Link href={"/"}>Home</Link>
            </button>
            <button className=" pl-2.5 pr-2.5 text-2xl hover:text-green-500">
              <Link href={"/About"}>About</Link>
            </button>
            <button className=" pr-2.5 pl-2.5 text-2xl hover:text-red-700">
              <Link href={"/Contact"}>Contact</Link>
            </button>
            <button className=" pr-2.5 pl-2.5 text-2xl hover:text-green-500">
              <Link href={"/Skills"}>Skills</Link>
            </button>
            <button className=" pr-2.5 pl-2.5 text-2xl hover:text-red-700">
              <Link href={"/Why"}>Why me</Link>
            </button>
          </div>
        </header>
        {children}
        <footer className=" flex justify-center pt-7 pb-7 bg-black text-white">
          &copy; 2025 Ssebayigga Sharif. All rights reserved.
          <p className=" pl-3.5 pr-3.5">
            <Link
              href={"https://github.com/ssebayigga-sharif"}
              className=" hover:text-red-700"
            >
              Github
            </Link>
          </p>
          <p className=" pr-3.5 pl-3.5">
            <Link
              href={"https://www.linkedin.com/in/sharif-ssebayigga-7025a6375/"}
              className=" hover:text-green-500"
            >
              LinkedIn
            </Link>
          </p>
          <p className=" pl-3.5 pr-3.5"> sharifsseba@gmail.com.</p>
        </footer>
      </body>
    </html>
  );
}
